name: CI

on: pull_request

jobs:
  build-code:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8      
    - name: Checkout Code
      uses: actions/checkout@v2.0.0
    - name: Build Code
      run: mvn clean package
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: hello-shiftleft-0.0.1.jar
        # Directory containing files to upload
        path: target/
  shiftleft-code-analysis:
    runs-on: ubuntu-latest
    needs: build-code
    env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        GITHUB_REPO: "${{ github.repository }}"
        GITHUB_SHA: "${{ github.sha }}"
        GITHUB_REF: "${{ github.ref }}"
        SHIFTLEFT_ORG_ID: "${{ secrets.SHIFTLEFT_ORG_ID }}"
        SHIFTLEFT_ACCESS_TOKEN: "${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}"
        SHIFTLEFT_API_TOKEN: "${{ secrets.SHIFTLEFT_API_TOKEN }}"
    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download artifact
      uses: actions/download-artifact@v1.0.0
      with:
        # Artifact name
        name: hello-shiftleft-0.0.1.jar
    - name: Checkout Code
      uses: actions/checkout@v2.0.0  
    - name: Analyze code
      run: sh actionanalysis.sh

